name: language_pickers2
description: It makes language select pickers for you in Flutter. You can use it freely in lots of ways.
version: 1.0.0
homepage: https://github.com/cybex-dev/flutter_language_pickers2
repository: https://github.com/cybex-dev/flutter_language_pickers2
documentation: https://github.com/cybex-dev/flutter_language_pickers2/wiki
issue_tracker: https://github.com/cybex-dev/flutter_language_pickers2/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter